add args to config
ATTron/merlin pull request #8
Opened 2019-10-22 00:48 UTC by jrwren

2019-10-22 00:48 UTC, jrwren commented
for #4

2019-10-25 15:25 UTC, ATTron requested changes
Thanks for the help! If you could make this one small change I can merge this in. Would you also be able to update the README to include your changes? Specifically adding it to this section:

The config.json file takes the following arguments:
```
   WatchDir  <- The directory for Merlin to watch
   OutputDir <- Directory that Merlin will store output files
   Encoder   <- The chosen encoder format (run HandBrakeCLI --help to see list of available encoder formats)
   Preset    <- The HandBrakeCLI presets (run HandBrakeCLI -z to see available video presets)
   Format    <- The output format for the encoded files (av_mp4, av_mkv, av_webm)
```

2019-10-25 15:25 UTC, ATTron commented on encoder/encoder.go
> +		"-Z", config.Preset, "--decomb=bob"}
the ``` --decomb=bob ``` should be removed here as it will be handled by the ``` config.Args ``` call on line 16

2019-10-25 18:18 UTC, ATTron approved these changes

2019-10-25 18:18 UTC, merged

2019-10-25 18:18 UTC, ATTron commented
@jrwren merged. Thanks!